---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon CodePipeline - Project for SecureStore on EKS IaC'

Parameters:
  SecureStoreEksBuildProjectName:
    Description:  The name of the CodeBuild project
    Type: String
    Default: SecureStoreEks
  SecureStoreEksIAMPxSx:
    Description: Generic prefix/suffix for IAM resources (role, policy)
    Type: String
    Default: SecureStoreEks
  SecureStoreRDSSnapshotName:
    Description: Name of the existing RDS snapshot of the SecureStore DB
    Type: String
    Default: secstorewkc003
  
Resources:
  EksServicePolicyWAccount:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${SecureStoreEksIAMPxSx}-SvcPolicy'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
          - Effect: Allow
            Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:PutItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:UpdateItem'
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/SecStoreAndMoreAdmin
      Roles:
        - !Ref EksServiceRole
  EksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${SecureStoreEksIAMPxSx}-SvcRole'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/SecStoreRDSFckNatIAM
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/SecStoreRDSFckNat
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/SecSetoreEksCluster
  EksCodeBuildProject:
    Type:  AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Description:  Builds the EKS infrastructure (including RDS DB, FckNat instances for NAT and EKS cluster/node groups)
      Environment:
        ComputeType: BUILD_LAMBDA_1GB
        Type: LINUX_LAMBDA_CONTAINER
        Image: "aws/codebuild/amazonlinux-x86_64-lambda-standard:python3.11"
      Name: SecStoreEksInf
      Source:
        BuildSpec: buildspec/buildspec-eksinf.yaml
        Type: GITHUB
        #TODO maybe move to an SSM parameter
        Location: https://github.com/cjcatchings/securestore-admin.git
      SourceVersion: develop
      ServiceRole: !Ref EksServiceRole

Outputs:
  EksCodeBuildProjectArn:
    Description:  The ARN of the EKS CodeBuild Project
    Value: !GetAtt EksCodeBuildProject.Arn